name: build-docs

on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd docs
          npm ci
      - name: Build
        run: |
          cd docs
          npm run build
